package com.homefooddelivery.models;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

@Entity
@Table(name = "products")
public class Product {
	// An autogenerated id (unique for each user in the db)
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private int id;
	  
	@NotNull
	private String nombre;
	  
	@NotNull
	private long precio;
	  
	@NotNull
	private String unidad;

  // Public methods
	  
	public Product() { }
	
	public Product(int id) { 
		this.id = id;
	}

	public String getNombre() {
		return nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public long getPrecio() {
		return precio;
	}

	public void setPrecio(long precio) {
		this.precio = precio;
	}

	public String getUnidad() {
		return unidad;
	}

	public void setUnidad(String unidad) {
		this.unidad = unidad;
	}

	public Product(String nombre, long precio, String unidad) {
		super();
		this.nombre = nombre;
		this.precio = precio;
		this.unidad = unidad;
	}

	@Override
	public String toString() {
		return "Product [id=" + id + ", nombre=" + nombre + ", precio=" + precio + ", unidad=" + unidad + "]";
	}
	    
}
